### ISSUE TITLE
[BUG] The window opens in another window, not a new one.

### ISSUE THREAD

**Issue by mike2003** [schroef/Custom-Preferences-Size#1]
**OS:** Windows 10 x64, blender-3.0.1-windows-x64

**ADDON:** Custom-Preferences-Size-v001

Wrong window to display.
When I run the command, the settings window opens in another window that I already have.
I have two monitors, and the second one already has separate windows.
Standard settings open a new window.
But this addon uses the old window.

![2022-02-22_03-47-38](https://user-images.githubusercontent.com/11754198/155043303-b2e66abb-d712-452a-98cd-3f7c80f23480.jpg)
![2022-02-22_03-48-13](https://user-images.githubusercontent.com/11754198/155043331-c1117776-12ec-4c6d-bdb3-282791d1c84e.jpg)

**Comment by schroef** [comment]
Hi and thanks for reporting. That must have been an API change then, normally the command "New Window" open a new one each time you run it. Its this command what i make use of.

Ive not tried 3.0 branch yet, will have a look at it. In bl 2.83 and 2.93 still works fine

![custom-preferences](https://user-images.githubusercontent.com/6923008/155147023-997a9d32-c9ae-4fce-b097-9549b1c93e4b.gif)

EDIT
Okay, seem i used a different apprach. Could you perhaps try something on your end. Could you edit the _init_.py file in the folder `Custom-Preferences-Size`. Then find line 46 and add this above the operator call `bpy.ops.wm.window_new()`
So line 46 is this; `bpy.ops.render.view_show("INVOKE_DEFAULT")` and restart Blender

**Comment by schroef** [comment]
If that doenst work, check in the preferences > Interface > Editors > Temporary Windows then check what happens if you set Render to "New Window". Also remove that extra line in the _ini_.py file and restart Blender.

Im almost 100% certain its this setting, I alway set it to New Window. Lets hop this works for you now

**Comment by mike2003** [comment]
``

**Comment by mike2003** [comment]
> bpy.ops.wm.window_new()

It looks like it works.
