### ISSUE TITLE
Window size is not remembered in Blender 3.5+[BUG]

### ISSUE THREAD

**Issue by panbeep** [schroef/Custom-Preferences-Size#2]
Window size is not remembered in Blender 3.5+ beta version.

**Comment by panbeep** [comment]
Looks like Blender 3.4 is also affected

**Comment by schroef** [comment]
I'll need to test those versions. It should work as i save the window size to a settlng and that is used when opening the custom preferences window. I'll have a look at ir

**Comment by schroef** [comment]
> Window size is not remembered in Blender 3.5+ beta version.

PS you did put in the dimension under the addon, correct?

![Screen Shot 2023-03-14 at 10 10 34](https://user-images.githubusercontent.com/6923008/225030145-087203dc-4c2d-40c0-af7e-8a97b8e96472.png)

**Comment by panbeep** [comment]
I'm not sure what happened before, but after the system restart it works as expected now.
Thank you for checking this out!

**Comment by schroef** [comment]
I dont recall, but perhaps this needs a restart in order for it to read the settings. Though it should not matter.

Ill test that part and see what happens.

Hope this simple addon can help you.

EDIT
Well tried it and worked as it should. Not sure what happened but glad it got solved
